name: Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 1 * *" # monthly

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: fri_vendor
          target-ros2-distro: foxy
